### ISSUE TITLE
Please don't steal my account to star your own repo!

### ISSUE THREAD

**Issue by e-kiss-me** [LIANGKE23/Awesome-Knowledge-Graph-Reasoning#2]
I don't like it!

**Comment by LIANGKE23** [comment]
> I don't like it!

?I swear that I really don't do that

**Comment by LIANGKE23** [comment]
I swear I really don't do that. Really you can cancel it as you like. I really don't steal it. I really don't need to do it

**Comment by LIANGKE23** [comment]
> 
I am very sorry that your GitHub account is stolen. But you can cancel it as you like. But I don't need to steal someone's GitHub for staring. If I need stars, I can create some by myself.

**Comment by LIANGKE23** [comment]
> I don't like it!
I am very sorry that your GitHub account is stolen. But you can cancel it as you like. But I don't need to steal someone's GitHub for staring. If I need stars, I can create some by myself.

**Comment by LIANGKE23** [comment]
> I don't like it!

I am very sorry that your GitHub account is stolen. But you can cancel it as you like. But I don't need to steal someone's GitHub for staring. If I need stars, I can create some by myself.
