### ISSUE TITLE
How were the dataset statistics mentioned in the paper obtained?

### ISSUE THREAD

**Issue by CuiJie98** [LIANGKE23/Awesome-Knowledge-Graph-Reasoning#8]
![image](https://user-images.githubusercontent.com/91528390/234199581-bc4a87d5-c695-4eb0-8327-f1a9cf93ba7c.png)

From the download link of the wn18rr dataset you gave, I found that the entity and other related data do not match. How did you get the data?
Related issues arise with other datasets, such as FB15k-237.

Hope to answer~

**Comment by LIANGKE23** [comment]
We collected these statistics from the paper using WN18RR and then directly adopted the related data set used in their open-source code. I am very sorry that we have overlooked this detail, and I believe the difference in quantity should not be huge.

But anyway, thanks for your suggestions and we will correct them ASAP.

**Comment by LIANGKE23** [comment]
We have corrected WN18RR and FB15k-237. And will double-check all of the links and datasets. Thanks for your question!

**Comment by LIANGKE23** [comment]
We have double checked and corrected the other datastes.
